#!/bin/bash

echo "Installing Claude Session Manager..."

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Make all scripts executable
echo "Making scripts executable..."
chmod +x "$SCRIPT_DIR"/*.sh

# Create Claude commands directory
echo "Creating Claude commands directory..."
mkdir -p ~/.claude/commands

# Generate the save command with the correct path
echo "Installing /session-save command..."
if [ -f ~/.claude/commands/session-save.md ]; then
    echo "Backing up existing session-save.md to session-save.md.bak"
    mv ~/.claude/commands/session-save.md ~/.claude/commands/session-save.md.bak
fi

# Create session-save.md with the actual installation path
cat > ~/.claude/commands/session-save.md << EOF
---
prefix: session
bash: true
---

# Save Session

This command saves the current Claude Code session with a given name for later retrieval.

## Usage

\`\`\`
/session:save <session-name>
\`\`\`

Where \`<session-name>\` is a descriptive name for your session.

## Example

\`\`\`
/session:save "Bug fix discussion"
/session:save "Feature planning meeting"
\`\`\`

---

\`\`\`bash
# This file was generated by claude-session-manager install.sh
# Installation path: $SCRIPT_DIR
"$SCRIPT_DIR/save_session.sh" "\$1"
\`\`\`
EOF

# Create alias for easy access (optional)
echo
echo "Installation complete!"
echo
echo "Installed from: $SCRIPT_DIR"
echo
echo "Usage:"
echo "  1. In Claude: /session:save \"Your Session Name\""
echo "  2. In terminal: $SCRIPT_DIR/session_manager.sh"
echo
echo "You may want to add an alias to your shell config:"
echo "  alias claude-sessions='$SCRIPT_DIR/session_manager.sh'"
echo
echo "To uninstall: rm ~/.claude/commands/session-save.md"
echo

# Check for old sessions
if [ -d "$HOME/.claude-sessions" ]; then
    echo "Note: Found sessions in old location (~/.claude-sessions/)"
    echo "Run ./migrate_sessions.sh to move them to the new location"
    echo
fi

echo "Sessions are now stored in: $SCRIPT_DIR/sessions/"
echo
echo "Enjoy!"